### ISSUE TITLE
Unclear how to update the version number in a spec

### ISSUE THREAD

**Issue by iosdev-republicofapps** [CocoaPods/Specs#12885]
Hi,

I'm trying to use MMMarkdown through CocoaPods.  The author of MMMarkdown doesn't use CocoaPods and doesn't want to include pod specs in his original MMMarkdown repo.  That's fine, that's his choice and he's been good about supporting MMMarkdown and it's a wonderful piece of code.

A new version of MMMarkdown was just released, 0.4, and I wanted to create a pod spec for that.  It's not clear to me how to do this.  **What's the easiest way to do this?**

Here are my problems:

1. I can't find out who the owner of the pod spec is ... the pod trunk command doesn't seem to have a subcommand to find out who the owners or contributors are and it won't let me add myself as the owner.
2. Github barfs on the specs repo and I can't seem to see the commit authors on https://github.com/CocoaPods/Specs/tree/master/Specs/MMMarkdown
3. All I see in the specs repo is a .podspec.json file and yet the documentation at http://guides.cocoapods.org/making/specs-and-specs-repo.html talks about needing to create the spec in the Ruby DSL .podspec format and how pod trunk push converts the pod spec to json.  Is it possible to pod trunk push the .podspec.json file?

Literally, all I need to do is take the existing file at https://github.com/CocoaPods/Specs/blob/master/Specs/MMMarkdown/0.3/MMMarkdown.podspec.json and change two instances of 0.3 to 0.4 and upload as version 0.4 and I'm done!  How can I do that?

Can I not just git push to the CocoaPods/Specs repo?

I'm not trying to be a whiner or complain - I really love CocoaPods and all the hard work you do for us!  But it seems like the cocoa pods guides are out-of-date with respect to json pods and it's not clear how to do a simple update like this when the original code author doesn't wan't to use CocoaPods.

I really want to help with creating a 0.4 version of MMMarkdown but I don't see how.  Please help!  :-)

**Comment by Keithbsmiley** [comment]
> I can't find out who the owner of the pod spec is

MMMarkdown isn't currently owned. There is a built in command to tell you this information coming in a future version of CocoaPods.

> Is it possible to pod trunk push the .podspec.json file?

Yes.

> Literally, all I need to do is take the existing file at and change two instances of 0.3 to 0.4 and upload as version 0.4 and I'm done! How can I do that?

Claim the spec, bump the versions, push the JSON.

> Can I not just git push to the CocoaPods/Specs repo?

No, it has to go through trunk.

> But it seems like the cocoa pods guides are out-of-date with respect to json pods

We still recommend you write the ruby versions. The JSON versions on trunk are really just an implementation detail.

> it's not clear how to do a simple update like this when the original code author doesn't wan't to use CocoaPods.

Yea. This is because this is just a crappy situation. In theory you could claim MMMarkdown and then be the owner of the spec, meaning that you could push new versions as the library releases them. Even though the library maintainer doesn't want to.

**Comment by Keithbsmiley** [comment]
Also it would be ideal, assuming the author is willing, to just ask them to submit a new version of the spec when they tag the repo. Obviously this doesn't always work out.

**Comment by iosdev-republicofapps** [comment]
Hi Keith,

Thanks so much for responding so quickly, I really appreciate your help!

Since I was already hosting the pod spec in my own fork of MMMarkdown and have verified that 0.4 builds fine, could I just do the following:

1. Download https://github.com/CocoaPods/Specs/blob/master/Specs/MMMarkdown/0.3/MMMarkdown.podspec.json to ~/MMMarkdown.podspec.json
2. Change the two occurrences of "0.3" to "0.4"
3. pod trunk push MMMarkdown.podspec.json

I don't have "the library's folder" as mentioned in http://guides.cocoapods.org/making/getting-setup-with-trunk.html so I don't know if the lint will pass.  I don't have time to convert the json pod spec to the Ruby version, sorry.  Where would the original Ruby version be (from before the conversion to json)?

Will this work or is trunk expecting me to have the full pod directory setup for MMMarkdown - I don't have time for that.  I literally just need to change 0.3 to 0.4 ... :-)

Sorry, I'm not trying to be lazy, I'm trying to help out by publishing the 0.4 release for the owner to all cocoa pods users.  I might have more time later, but I'm on a tight deadline for a project right now ...

Thanks and please let me know how I can help!

**Comment by Keithbsmiley** [comment]
The lint should work fine just from the spec, it will download the source repo and check it. You don't have to convert the spec to ruby, just update the json one and push it.

**Comment by iosdev-republicofapps** [comment]
Thanks Keith!

However, pod doesn't seem to want to pull down the new files.  In my test project that uses MMMarkdown, I have:

````
# Podfile
pod 'MMMarkdown', :git => 'https://github.com/iosdev-republicofapps/MMMarkdown.git'
````

However neither pod update or pod install will bring down the new files from 0.4.  It seems like pod is confused.  Why doesn't it see the new 0.4 files?

Note that the pod spec is hosted at https://github.com/iosdev-republicofapps/MMMarkdown.git and it has both version and tag set to 0.4 but the actual source being pulled for the pod is from the original code author's repo at https://github.com/mdiep/MMMarkdown

Any ideas why I can't get pod to pull the new 0.4 code?

**Comment by Keithbsmiley** [comment]
I would delete your local cached copy by removing it from your Pods folder and do a reinstall.

**Comment by iosdev-republicofapps** [comment]
Here is my test project's Podfile if it helps:
````
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'MMMarkdown', :git => 'https://github.com/iosdev-republicofapps/MMMarkdown.git'
#pod 'MMMarkdown', '~> 0.3'

target 'MarkdownTestMM' do

end

target 'MarkdownTestMMTests' do

end
````

Here is the output of running `pod update --verbose``:
````
Update all pods
  Preparing

Analyzing dependencies

Updating spec repositories
  $ /usr/bin/git rev-parse  >/dev/null 2>&1
Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.

CocoaPods 0.36.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.


Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MarkdownTestMM`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MarkdownTestMMTests`: (``)

Finding Podfile changes
  - MMMarkdown

Fetching external sources
-> Pre-downloading: `MMMarkdown` from `https://github.com/iosdev-republicofapps/MMMarkdown.git`, commit `7519b592e984bcd9c35fa1fecaf0774cd315b038`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/iosdev-republicofapps/MMMarkdown.git /Users/joel/src/XcodeDemos/MarkdownTestMM/Pods/MMMarkdown
     Cloning into '/Users/joel/src/XcodeDemos/MarkdownTestMM/Pods/MMMarkdown'...
   $ /usr/bin/git checkout -b activated-commit 7519b592e984bcd9c35fa1fecaf0774cd315b038
   Switched to a new branch 'activated-commit'

Resolving dependencies of `Podfile`
Starting resolution (2015-01-02 11:51:38 -0800)
Creating possibility state for MMMarkdown (from `https://github.com/iosdev-republicofapps/MMMarkdown.git`) (1 remaining)
  Attempting to activate MMMarkdown (0.3)
  Activated MMMarkdown at MMMarkdown (0.3)
  Requiring nested dependencies ()
  Creating possibility state for MMMarkdown (from `https://github.com/iosdev-republicofapps/MMMarkdown.git`) (1 remaining)
    Attempting to activate MMMarkdown (0.3)
    Found existing spec (MMMarkdown (0.3))
    Creating possibility state for MMMarkdown (from `https://github.com/iosdev-republicofapps/MMMarkdown.git`) (1 remaining)
      Attempting to activate MMMarkdown (0.3)
      Found existing spec (MMMarkdown (0.3))
Finished resolution (3 steps) (Took 0.003741 seconds) (2015-01-02 11:51:38 -0800)
Unactivated: 
Activated: MMMarkdown

Comparing resolved specification to the sandbox manifest
  M MMMarkdown

Downloading dependencies

-> Installing MMMarkdown 0.3 (was 0.3)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Pods-MMMarkdown` OS X 10.10
    - Installing target `Pods-MarkdownTestMM-MMMarkdown` OS X 10.10
    - Installing target `Pods-MarkdownTestMMTests-MMMarkdown` OS X 10.10
    - Installing target `Pods` OS X 10.10
    - Installing target `Pods-MarkdownTestMM` OS X 10.10
    - Installing target `Pods-MarkdownTestMMTests` OS X 10.10
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods` (`MarkdownTestMM.xcodeproj` project)
````

It is not pulling down the changes ... :-(  I can see that many of the changes that went into 0.4 are not being pulled down.

Why is pod still talking about 0.3 when the pod spec.json only references 0.4?

**Comment by iosdev-republicofapps** [comment]
Should I just delete `Pods/MMMarkdown` to delete it from my local cache?  Or do I need to remove other files like Xcode schemes and such?

**Comment by iosdev-republicofapps** [comment]
I deleted all of the following files:
````
./Headers/Build/MMMarkdown
./Headers/Build/MMMarkdown/MMMarkdown.h
./Headers/Public/MMMarkdown
./Headers/Public/MMMarkdown/MMMarkdown.h
./Local Podspecs/MMMarkdown.podspec.json
./MMMarkdown
./MMMarkdown/Source/MMMarkdown.h
./MMMarkdown/Source/MMMarkdown.m
````

It still doesn't work.  I still get:
````
Pre-downloading: `MMMarkdown` from `https://github.com/iosdev-republicofapps/MMMarkdown.git`, commit `7519b592e984bcd9c35fa1fecaf0774cd315b038`
Downloading dependencies
Installing MMMarkdown 0.3 (was 0.3)
````

Where is it getting 0.3 from?  And I don't specify commit 7519b592e984bcd9c35fa1fecaf0774cd315b038 anywhere ...

Do I need to apply the 0.4 git tag to my forked MMMarkdown repo, the one where I'm pulling the pod spec from?  I thought it was enough that the tag was on the actual repo where the pod code is coming from, the master MMMarkdown, not my fork.

**Comment by iosdev-republicofapps** [comment]
OK, the following seems to have forced pod to download 0.4:
````
rm -rf Pods/
rm Podfile.lock
````
It seems like the Podfile.lock had the version stuck at 0.3 and refused to download 0.4 even though the Podspec in my fork listed 0.4.  Is this maybe a bug in how :git pod specs are handled?

**Comment by iosdev-republicofapps** [comment]
Yay!  Pushed:
````
Joels-MacBook-Air:MMMarkdown joel$ pod trunk push MMMarkdown.podspec.json 
Validating podspec
 -> MMMarkdown (0.4)

  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/0fe6d330820a26a09845e7f9cdb01797077e6663/Specs/MMMarkdown/0.4/MMMarkdown.podspec.json
  - Log messages:
    - January 2nd, 12:14: Push for `MMMarkdown 0.4' initiated.
    - January 2nd, 12:14: Push for `MMMarkdown 0.4' has been pushed (1.051914358 s).
````

One last question.  I keep trying `pod search MMMarkdown` to see if my update is available but it doesn't list 0.4.  The only way to see 0.4 was to do 'pod spec update`.  Then pod search returned 0.4.  Do others need to do pod spec update to see this new version?  Isn't the search remote or only local?

Anyway, thanks for all of your help and sorry for so many questions, I know you're busy and I appreciate you taking the time to help me!

**Comment by Keithbsmiley** [comment]
Ah yes it wouldn't download 0.4 because you hadn't pushed it yet. So you can lint the spec, but not include it in your project.

**Comment by Keithbsmiley** [comment]
`pod repo update` is performed automatically when running many commands, so no users shouldn't have to worry about it.
