### ISSUE TITLE
how long will my kit be deployed (WTRequestCenter)

### ISSUE THREAD

**Issue by swtlovewtt** [CocoaPods/Specs#12905]
thank you

**Comment by squarefrog** [comment]
I don't understand your question. Are you asking how long until your pod shows up? It's already in the [Specs repo](https://github.com/CocoaPods/Specs/blob/d518e96e4aafc2d74fe93d0fe18a313c32906ad2/Specs/WTRequestCenter/0.5.1/WTRequestCenter.podspec.json) and [online](http://cocoapods.org/?q=WTRequestCenter), if it's not showing up locally, run the following command in Terminal:

    pod repo update

**Comment by squarefrog** [comment]
You should also make the effort to fill in your Pods description.
