### ISSUE TITLE
Hi! I have a little problem.

### ISSUE THREAD

**Issue by xhzengAIB** [CocoaPods/Specs#12909]
Hi! 
I run pod trunk register xhzengAIB@gmail.com "Jack"

I click the link ok.

But: 
pod trunk push XHScrollMenu.podspec 
Validating podspec
 -> XHScrollMenu (1.0)

[!] You are not allowed to push new versions for this pod.

Why?

Jack

**Comment by Keithbsmiley** [comment]
You must first claim the spec http://blog.cocoapods.org/Claim-Your-Pods/
