### ISSUE TITLE
Missing headers (build 8005.2.0)

### ISSUE THREAD

**Issue by chebur** [CocoaPods/Specs#12908]
Latest available build 8005.2.0 is missing RTC* headers. Decided to rollback to the build 7972.2.0 which has headers.

**Comment by squarefrog** [comment]
I'm not entirely sure what you are asking here? Was this supposed to be posted to a pods issue page rather than here?

**Comment by chebur** [comment]
I'm sorry, you're right. Should've posted this to the correct place. Thank you.
