### ISSUE TITLE
Command to show all Pod owners

### ISSUE THREAD

**Issue by jameswangz** [CocoaPods/Specs#12904]
Hi,

Can we add a new command to show all owners for given pod, I only know I can use "pod trunk me" to show all pods for given user,  but the reverse relation should be helpful for the owner.

Thanks,
James

**Comment by squarefrog** [comment]
https://github.com/CocoaPods/cocoapods-trunk/issues/15 discussed this. You can use the following command to get a list of owners

    pod trunk info AFNetworking
