### ISSUE TITLE
Seems currently v3.10 available

### ISSUE THREAD

**Issue by googoodalls** [CocoaPods/Specs#12912]
Hello, Experts.

Seems currently v3.10 is available.
if possible, the official pod specs can be updated to v3.10 ?

http://dl.google.com/googleanalyticsservices/GoogleAnalyticsServicesiOS_3.10.zip

BR

Steven

**Comment by squarefrog** [comment]
$ pod search googleanalytics

returns:

    -> GoogleAnalytics-iOS-SDK (3.10)
       GoogleAnalytics for iOS SDK.
       pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
       - Homepage: https://developers.google.com/analytics/devguides/collection/ios/
       - Source:   https://dl.google.com/googleanalyticsservices/GoogleAnalyticsServicesiOS_3.10.zip
       - Versions: 3.10, 3.0.9, 3.0.8, 3.0.7, 3.0.6, 3.0.3, 3.0.3c, 3.0.3a, 3.0.2, 3.0.1, 3.0, 2.0beta4, 1.5.1,
       1.4 [master repo]
       - Subspecs:
         - GoogleAnalytics-iOS-SDK/Core (3.10)
         - GoogleAnalytics-iOS-SDK/IDFA (3.10)

Looks like it's already available?
