### ISSUE TITLE
Closing the CocoaPods/Push team

### ISSUE THREAD

**Issue by orta** [CocoaPods/Specs#12910]
Hey there @CocoaPods/push I'm going to remove the team. It's not that I don't particularly distrust you lot as members, but that I don't think anyone needs access anymore and it's always better to reduce the scope for things going wrong.

:+1: 

Will close this issue and delete team tomorrow. I remember 3+ years ago when I got push access, it was the first step towards something much, much bigger. Yet it was the first step, that's important. I hope you're all doing something awesome. You're always welcome to contribute in other ways.

**Comment by supermarin** [comment]
![](http://i.imgur.com/FHo7ng8.gif)

**Comment by ashfurrow** [comment]
Makes sense. I remember when I got push access – it changed a lot about how I saw collaboration online.

**Comment by AliSoftware** [comment]
Same here, what an epic moment it was! :dancer:

**Comment by yas375** [comment]
:+1:

**Comment by listrophy** [comment]
![colbert](http://www.reactiongifs.com/r/bakis.gif)
