### ISSUE TITLE
CocoaPods search finds podspec under wrong name

### ISSUE THREAD

**Issue by boredzo** [CocoaPods/Specs#12926]
Apologies if this is the wrong place to file a bug about the search on the CocoaPods webpage.

If you [search the CocoaPods website for “iso-8601-date-formatter”](http://cocoapods.org/?q=iso-8601-date-formatter), that's exactly what it finds, complete with a description and a [link to the site](http://boredzo.org/iso8601dateformatter/). The [Docs](http://cocoadocs.org/docsets/iso-8601-date-formatter/0.7) and [Spec](https://github.com/CocoaPods/Specs/tree/master/Specs/iso-8601-date-formatter/0.7/iso-8601-date-formatter.podspec.json) links, however, don't work; they refer to “iso-8601-date-formatter”, where [the correct name of the podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/ISO8601DateFormatter/) is “ISO8601DateFormatter”.

**Comment by squarefrog** [comment]
It appears as both when you [do a websearch](http://cocoapods.org/?q=iso).

**Comment by boredzo** [comment]
I'll clarify the wording of the original report. Web search is what I was talking about.

So, the web search can find it both ways, but only one of them works: ISO8601DateFormatter is correct; iso-8601-date-formatter's Docs and Spec links are 404.

**Comment by Keithbsmiley** [comment]
Submitted an issue to get this removed. Thanks! https://github.com/CocoaPods/trunk.cocoapods.org/issues/125
