### ISSUE TITLE
AFNetworking-MUResponseSerializer pointing to 404 repo

### ISSUE THREAD

**Issue by vincentkjj** [CocoaPods/Specs#12932]
Hi,

I found that AFNetworking-MUResponseSerializer spec points to https://github.com/Ulianko/AFNetworking-MUResponseSerializer.git, which currently returns 404.

Is this link no longer used? Could you fix the repo or update the link?

**Comment by Keithbsmiley** [comment]
Looks like the owner has removed this repo. If you would like to submit a PR to remove the related specs that would be great!
