### ISSUE TITLE
Pod trunk push error

### ISSUE THREAD

**Issue by Rannie** [CocoaPods/Specs#12946]
push failed by error: 
 -> CoreDataParrot (0.1.0)
    - ERROR | [xcodebuild]  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker
Why? [podspec link](https://github.com/Rannie/CoreDataParrot/blob/master/CoreDataParrot.podspec)

**Comment by Keithbsmiley** [comment]
Sounds like you aren't using the CocoaPods beta that supports swift. See http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
