### ISSUE TITLE
ld: library not found for -lPods when I mix Swift and ObjC pods

### ISSUE THREAD

**Issue by georgbachmann** [CocoaPods/Specs#12959]
Hello,
in a project that I am working on, I want to use some swift pods and some non-swift pods.
So I added GPUImage and tried using it but when compiling i get `ld: library not found for -lPods`
I already did clean and even delete all pods (incl. the project file) and made a new pod install. I have 0.36.0.beta.2 of cocoapods installed...

Is this a known issue? Or is there a workaround?

Here's my pod file:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'

    pod 'Alamofire', '~> 1.1'
    pod 'GPUImage', '~> 0.1.6'

**Comment by Keithbsmiley** [comment]
Please check for issues or post this on the main repo https://github.com/CocoaPods/CocoaPods/issues
