### ISSUE TITLE
OpenCV repo link is not reachable

### ISSUE THREAD

**Issue by alexmanzer** [CocoaPods/Specs#12969]
Hi,

At the moment the OpenCV pod points to a dead link:
http://skylink.dl.sourceforge.net/project/opencvlibrary/opencv-ios/2.4.10/opencv2.framework.zip

In general http://skylink.dl.sourceforge.net is not reachable anymore.

Could you fix the repo or update the link?

![bildschirmfoto 2015-02-19 um 10 56 51](https://cloud.githubusercontent.com/assets/1938527/6264672/12835528-b826-11e4-9d3c-eafaade5042e.png)

**Comment by squarefrog** [comment]
Looks like the project has moved to https://github.com/Itseez/opencv I think this would be a valid reason to submit a [Pull Request](https://github.com/CocoaPods/Specs/pull/12199)
