### ISSUE TITLE
Boost is missing circular_buffer files

### ISSUE THREAD

**Issue by mikeakers** [CocoaPods/Specs#12962]
The Boost pod is missing some files that are required for circular_buffer to work:

<pre>
boost/circular_buffer/base.hpp
boost/circular_buffer/debug.hpp
boost/circular_buffer/details.hpp
boost/circular_buffer/space_optimized.hpp
</pre>

I'd like to add them to the spec but I'm not sure which subspec they would belong to. Or even if they should be in a new subspec. Any suggestions?

**Comment by squarefrog** [comment]
Looks like the pod owner/maintainer is @jcollas, you could try and contact him to discuss how to proceed.
