### ISSUE TITLE
TWRChartsNew spec

### ISSUE THREAD

**Issue by alloy** [CocoaPods/Specs#12974]
@Apolotary @chasseurmic

Hey folks,

_I would like to first make it very clear that this thread is **not** meant as place to have a discussion on the topic as to what is or what is not allowed. That is legalese that should foremost be handled by a license._

@Apolotary From our point of view, I have just one practical question at this point, which is if you’ve decided to take down the repo as I can no longer find it at https://github.com/Apolotary/TWRCharts or elsewhere on your account? And, if so, if the TWRChartsNew spec should be removed as well?

**Comment by Apolotary** [comment]
Hi, 

Yes, please remove the repo. I’ve made a mistake by creating a public podspec instead of a private one. 

and also the main developer is kinda freaking out which concerns me

Best regards,
Bektur

**Comment by chasseurmic** [comment]
Nothing to be concerned about. It's just common sense and respect for the work of others.

**Comment by alloy** [comment]
Thanks for answering in a timely fashion :+1: We will remove the repo from the index.

**Comment by alloy** [comment]
Done in 15c2f52fb95b51879737f0d6721c57aaf52e0844.
