### ISSUE TITLE
Google Maps iOS SDK 1.9.2 - Minimum req. iOS7 ?

### ISSUE THREAD

**Issue by tarokker** [CocoaPods/Specs#12976]
Latest podspec reports ios7 as minimum requirement for Google Maps iOS SDK 1.9.2:

https://github.com/CocoaPods/Specs/blob/master/Specs/Google-Maps-iOS-SDK/1.9.2/Google-Maps-iOS-SDK.podspec.json

Is this an error? Google examples from original ZIP file works successfully with ios6.0. 
This podspec broke also my ios6.0 compatibility :(

**Comment by squarefrog** [comment]
That change was made by @domesticmouse in https://github.com/CocoaPods/Specs/pull/12973 I suggest you look at the notes for that Pull Request or contact the author of that Pull Request.

**Comment by domesticmouse** [comment]
See https://github.com/CocoaPods/Specs/pull/12980
