### ISSUE TITLE
Fabric.podspec missing AddressBook framework

### ISSUE THREAD

**Issue by markwhite00** [CocoaPods/Specs#12995]
I think the pod spec needs the following added to resolve linker errors when using v1.1.3

"frameworks": [
    “AddressBook"
  ],

**Comment by RyanCopley** [comment]
I noticed this as well...

**Comment by Keithbsmiley** [comment]
Please submit a PR for this fix. It will need to be okayed by @zergtmn

**Comment by RyanCopley** [comment]
I opened an issue with the Twitter team... I don't feel qualified to modify their pod spec

**Comment by Keithbsmiley** [comment]
Actually @zergtmn has no affiliation with Twitter (as far as I can tell) and they don't official support using CocoaPods as an installation method. But him submitting that fix is fine too, either way it would be best if he okayed it.

**Comment by zergtmn** [comment]
I've pushed 1.2.1 with a fix. Thanks!
