### ISSUE TITLE
Project not compiling after updating to cocoapods 36.0

### ISSUE THREAD

**Issue by Usipov** [CocoaPods/Specs#13003]
![2015-03-12 18 45 49](https://cloud.githubusercontent.com/assets/1080247/6621676/0a3b2f84-c8e9-11e4-9d56-ca43f7e1b17d.png)

Looks like you have changed a flag, standing for objc_sendSuper or objc_messageSend direct calls permitting

We tested, that updating pods using cocoapods 35.0 works fine

**Comment by orta** [comment]
This compiler flag is the new standard for Xcode projects from Apple since [Xcode 6](http://stackoverflow.com/questions/25852079/in-xcode6-gold-master-using-objc-msgsend-now-throws-a-syntax-error-saying-the-n), I'd recommend fixing this.
