### ISSUE TITLE
Getting a crash in unsolicited_mwi_on_rx_request

### ISSUE THREAD

**Issue by jodyscho** [CocoaPods/Specs#13016]
I've been getting a random crash. Looking into the crash report I see an access violation. Apparently this was fixed in 2.2. Are other's seeing this as well? I'll see if I can narrow down to the minimum config to reproduce.

http://trac.pjsip.org/repos/ticket/1753

**Comment by Keithbsmiley** [comment]
This is not the place to get help on this issue. Submit it upstream.
