### ISSUE TITLE
update pods for boost

### ISSUE THREAD

**Issue by StakshiGarg** [CocoaPods/Specs#13031]

**Comment by squarefrog** [comment]
We have just launched 'Trunk', which is the new way for you to submit your Pods. For more information on this have a read through the post at http://blog.cocoapods.org/CocoaPods-Trunk/ If you have previously had your Pod merged into the master repository, please ensure you claim your Pod http://blog.cocoapods.org/Claim-Your-Pods/

**Comment by StakshiGarg** [comment]
Hi,

I tried using trunk but i get this message. Can you please help.  
pod trunk push Specs/boost/1.57.0/

[!] Found podspec `Specs/boost/1.57.0/boost.podspec.json`
Validating podspec
 -> boost (1.57.0)

[!] You are not allowed to push new versions for this pod.
