### ISSUE TITLE
TestFlightSDK no longer exists

### ISSUE THREAD

**Issue by kylefleming** [CocoaPods/Specs#13034]
The TestFlight service no longer exists (https://developer.apple.com/testflight/update/). As such, the TestFlightSDK pod can't be installed anymore. It references a zip file that is no longer accessible (https://d193ln56du8muy.cloudfront.net/sdk/1397516197/TestFlightSDK3.0.2.zip).

What's the proper protocol for flagging this in the podspec? The 2 easiest things that come to mind are 1) remove all traces of the pod. 2) remove the actual install part from the podspecs and leave a fatal warning so that if someone tries to install it, at least they receive instructions that they need to remove it.

**Comment by squarefrog** [comment]
The spec should be marked as deprecated. Developers should receive a warning next time they update or install.

**Comment by Keithbsmiley** [comment]
Honestly since the source is gone it barely matters that the spec is there. But deprecation is a good first step. I'll be happy to remove it soon after.

**Comment by squarefrog** [comment]
Ok let's deprecate for a couple of weeks the remove it. You're right that it barely matters, so it's academic what happens now.

**Comment by Keithbsmiley** [comment]
https://github.com/CocoaPods/Specs/pull/13072
