### ISSUE TITLE
What is the process to modify a deployed pod?

### ISSUE THREAD

**Issue by mbishop-fiksu** [CocoaPods/Specs#13101]
Hello CocoaPods,

I haven't seen anything about this in the documentation, but how do I modify a cocoapod that I've deployed? I'm interested in these user-cases:

1. Redeploy the same version but with a different SHA.
2. Remove a deployed version completely (or mark it as deleted).

I'm assuming the best way is to fork the Specs repo, modify it myself and issue a PR. Is that the endorsed method though?

**Comment by keith** [comment]
We cannot update unversioned specs (specs that point to a commit). If you'd like to add a new version the repository would have to be tagged. Then you'd push that new version via trunk.

You can mark a pod as [`deprecated`](https://guides.cocoapods.org/syntax/podspec.html#deprecated) or even better [`deprecated_in_favor_of`](https://guides.cocoapods.org/syntax/podspec.html#deprecated_in_favor_of) a new pod. For this you would have to submit a PR

**Comment by mbishop-fiksu** [comment]
Specifically, I'd like to re-submit the *same version* of:
https://github.com/CocoaPods/Specs/commit/85ee99209729514d968c686ef890abf5ea16054e
but as the file will have some bits changed the sha will be changed.

To accomplish this, do I simply use trunk and submit the same version again?

**Comment by keith** [comment]
Ah you can submit a PR for that.
