### ISSUE TITLE
libpd 0.8.0 is out

### ISSUE THREAD

**Issue by Morpheu5** [CocoaPods/Specs#13107]
Just a heads up.

**Comment by keith** [comment]
// @jasperblues

**Comment by jasperblues** [comment]
@Morpheu5 Do you mean someone has published a spec or someone *should* publish a spec?

**Comment by Morpheu5** [comment]
The latter – someone *should* publish a spec.

(unless one is out and I missed it)

**Comment by jasperblues** [comment]
OK, I'll build/test/publish one tomorrow.

**Comment by jasperblues** [comment]
Sorry - still haven't done this. Up to the eyeballs in client work. At the latest will do this weekend.

**Comment by Morpheu5** [comment]
Thanks, no rush on my part, it was just a heads up :)

**Comment by jasperblues** [comment]
I did some minor maintenance on a project that has libPd today, and realized that I had forgotten about this ticket. Is it still outstanding?

**Comment by jasperblues** [comment]
Created pull req. with updated podspec. As soon as merged will push to CocoaPods trunk. Sorry for the delay!

**Comment by Morpheu5** [comment]
Thanks! I believe 0.8.2 is out now… seems to be quite the moving target :) Anyway, thanks for your work, I'm sure 0.8.0 will be good enough for a while.
