### ISSUE TITLE
Repository not found: AFNetworking-MUResponseSerializer

### ISSUE THREAD

**Issue by acoard** [CocoaPods/Specs#13112]
Hi all,

I'm relatively new to iOS dev, so apologies if I've made any mistakes.  I'm trying to run pod install in a project that contains AFNetworking-MUResponseSerializer.

Here's the error I get:

    Installing AFNetworking-MUResponseSerializer 1.0.1 (was 1.0.0)
    [!] Error installing AFNetworking-MUResponseSerializer
    [!] /usr/bin/git clone https://github.com/Ulianko/AFNetworking-MUResponseSerializer.git /whatever/Pods/AFNetworking-MUResponseSerializer --single-branch --depth 1 --branch 1.0.1
    Cloning into '/whatever/Pods/AFNetworking-MUResponseSerializer'...
    remote: Repository not found.
    fatal: repository 'https://github.com/Ulianko/AFNetworking-MUResponseSerializer.git/' not found

I believe the file responsible can be [found here](https://github.com/CocoaPods/Specs/blob/master/Specs/AFNetworking-MUResponseSerializer/1.0.0/AFNetworking-MUResponseSerializer.podspec.json).  

Anyways, it looks like the author deleted this library.  If anyone can shed any light on it this would be appreciated.  My plan is to try and find a fork someone made on github and then just explicitly require the podfile to load that.

Thanks!

**Comment by keith** [comment]
Yep looks like the author deleted this.  ¯\_(ツ)_/¯
