### ISSUE TITLE
Support svn source

### ISSUE THREAD

**Issue by jigmelam** [CocoaPods/Specs#13162]
Dear CocoaPods community,

I've created a git specs repository and make a podspec file for a private library that on SVN (see below) but it not work (check by pod spec lint ..)
spec.source = { :svn => "svn://jigmelam@192.168.1.2:3838/svn/private/abclib/"}

Could you please tell me how can I do that? 

Thank you so much!

**Comment by keith** [comment]
This is possible https://guides.cocoapods.org/syntax/podspec.html#source
