### ISSUE TITLE
project should not build if any of the Copy Pods Resources run script is missing from Target configuration

### ISSUE THREAD

**Issue by grevolution** [CocoaPods/Specs#13167]
Hi, 

the pod install/update command changes the targets and adds couple of run scripts in the App Targets. one of them is Copy Pods Resources, if somehow that gets deleted there is no compile time error and the build compiles successfully without any flags raised. you only notice this when you get a runtime error when your code tries to access any of the bundled resources. there should be a compile time check on this.

**Comment by squarefrog** [comment]
I feel this would be better suited on the main [CocoaPods](https://github.com/CocoaPods/CocoaPods/issues) repo.
