### ISSUE TITLE
"fatal: reference is not a tree" when attempting to use cocos2d 1.1.rc0 pod

### ISSUE THREAD

**Issue by dburr** [CocoaPods/Specs#13208]
I'm maintaining some legacy code that uses an older version of cocos2d (1.1.rc0) however when I attempt to install said pod, I am getting the following error:

```
[!] Error installing cocos2d
[!] /usr/local/bin/git checkout -b activated-commit 7ee5b9abf645c32379a45317986a308204277bb1

fatal: reference is not a tree: 7ee5b9abf645c32379a45317986a308204277bb1
```

I checked the git repo referenced in the Cocoapods spec and there is indeed no commit with that tag.

**Comment by segiddins** [comment]
Nothing we can really do about that, I'd contact the owners of that pod.
