### ISSUE TITLE
Unavailable download url in OpenCV.podspec.json

### ISSUE THREAD

**Issue by mezi** [CocoaPods/Specs#13209]
http://code.opencv.org/issues/4418
The linked download url in Specs/Specs/OpenCV/2.4.10/OpenCV.podspec.json podspec are unavailable: "http://hivelocity.dl.sourceforge.net/project/opencvlibrary/opencv-ios/2.4.10/opencv2.framework.zip"

**Comment by segiddins** [comment]
I'd contact the owner of that pod.
