### ISSUE TITLE
Allow pushing of updates to podspec file

### ISSUE THREAD

**Issue by jaboutboul** [CocoaPods/Specs#13264]
Hi All,

Currently, it is impossible to do something like 'pod trunk push' to update a specfile. It would be great we would be able to push updates to a spec, instead of bumping the version number, especially for minor things like point releases and small updates.

**Comment by keith** [comment]
If your spec is broken, you can submit a pull request to update it. We highly discourage significant changes in these PRs. That is when you should bump the version number.
