### ISSUE TITLE
Unable to find my project 

### ISSUE THREAD

**Issue by wuwen1030** [CocoaPods/Specs#13287]
I have created my own project “XTOnePixelLine”, and I has pushed it to my forked project, and created a pull request. But I still can't find my project using "pod search XTOnePixelLine".
![fcaf65df-c4e1-4874-9154-904de11ebb7d](https://cloud.githubusercontent.com/assets/3377567/8638181/fb633ac2-28e4-11e5-96a8-eb634057afe5.png)

**Comment by keith** [comment]
As you can see that pull request was closed without being merged. Unless you followed the linked instructions in that comment it has not been added yet

**Comment by wuwen1030** [comment]
Thanks a lot.
