### ISSUE TITLE
Can't find my project 

### ISSUE THREAD

**Issue by wuwen1030** [CocoaPods/Specs#13290]
Sorry, I'm here again. I have open an issue [#13287](https://github.com/CocoaPods/Specs/issues/13287). And thank you for the answer, but I still don't know how to make that. Here's your answer.
```
As you can see that pull request was closed without being merged. Unless you followed the linked instructions in that comment it has not been added yet
```
I don't see any "the linked instructions", thanks again.

**Comment by segiddins** [comment]
Please read https://github.com/CocoaPods/Specs/pull/12199.

**Comment by wuwen1030** [comment]
Thanks a lot. I have solved the problem under guide of [https://guides.cocoapods.org/making/getting-setup-with-trunk.html](https://guides.cocoapods.org/making/getting-setup-with-trunk.html)
