### ISSUE TITLE
geos 3.4.2 installation error

### ISSUE THREAD

**Issue by obi-joan** [CocoaPods/Specs#13346]
Trying to install geos 3.4.2 returns this error:

hal9000-2:apGis obi-joan$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using FMDB (2.5)
Using GeodeticUTMConverter (1.0.7)
Installing geos (3.4.2)
[!] /bin/bash -c 
set -e

type -P autoconf &>/dev/null || alias autoconf 'xcrun autoconf'
type -P autoheader &>/dev/null || alias autoheader 'xcrun autoheader'
type -P aclocal &>/dev/null || alias aclocal 'xcrun aclocal'
type -P automake &>/dev/null || alias automake 'xcrun automake'
type -P glibtool &>/dev/null || alias glibtool 'xcrun glibtool'
type -P glibtoolize &>/dev/null || alias glibtoolize 'xcrun glibtoolize'

sh autogen.sh
./configure
./tools/svn_repo_revision.sh

sed -i "" "s/\/\* #undef HAVE_INT64_T_64 \*\//#define HAVE_INT64_T_64 1/" include/geos/platform.h
sed -i "" "s/#define HAVE_LONG_INT_64 1/\/\* #undef HAVE_LONG_INT_64 \*\//" include/geos/platform.h

cat <<EOT >> include/geos/platform.h
  #undef ISNAN
  #define ISNAN(x) (std::isnan(x))
EOT

/bin/bash: line 5: alias: aclocal: not found
/bin/bash: line 5: alias: xcrun aclocal: not found

I found older posts explaining the same problem, maybe the solution is on

alias autoconf='xcrun autoconf'

Thanks

**Comment by segiddins** [comment]
Please report this issue directly to the owner of the pod.
