### ISSUE TITLE
libais out of date

### ISSUE THREAD

**Issue by schwehr** [CocoaPods/Specs#13382]
https://github.com/CocoaPods/Specs/blob/master/Specs/libais/1.0.3/libais.podspec.json

Points to rolker.  That is a very old fork of libais.  https://github.com/schwehr/libais is very far ahead of Roland's fork.  Also, I've switched libais from LGPL to the Apache 2.0 license.

**Comment by segiddins** [comment]
Please contact the owner of the pod directly to push a new spec.

**Comment by schwehr** [comment]
And who is the owner?  github barfs on trying to get the history and I see no owner field in the the file.  As a non user of this, it's not obvious what is going on.  Yet I get people talking to me about this repo.

**Comment by segiddins** [comment]
`pod trunk info libais`

->

```
libais
    - Versions:
      - 1.0.3 (2014-05-19 21:56:12 UTC)
    - Owners:
      - Unclaimed <unclaimed-pods@cocoapods.org>
```
