### ISSUE TITLE
about how to use PromiseKit with cocoapods

### ISSUE THREAD

**Issue by bytegh** [CocoaPods/Specs#13425]
hey guys, 

I am planing to use PromiseKit in my project. but when I added the PromiseKit into the Podfile, and run the command "pod update", there is an error which tell me the pods can not be find. how can I solve this problem ?

-----
[!] Unable to satisfy the following requirements:

- `PromiseKit (~> 2.2.1)` required by `Podfile`
-----

thanks

**Comment by neonichu** [comment]
Most likely you have an incompatible deployment target, PromiseKit 2.2.1 needs at least iOS 8. An improved error message for this will be in the next release of CP.
