### ISSUE TITLE
boost missing .hpp files

### ISSUE THREAD

**Issue by dionysiusmarquis** [CocoaPods/Specs#13477]
I just switched from git submodule to CocoaPods and tried to install boost. Unfortunately I get following error:
``{projectdir}/Pods/boost/boost/type_index.hpp:29:13: 'boost/type_index/stl_type_index.hpp' file not found
``

actually the whole ``boost/type_index/`` folder is empty.

**Comment by keith** [comment]
Report this upstream.

**Comment by dionysiusmarquis** [comment]
?
