### ISSUE TITLE
Facebook iOS SDK - FBSDKShareKit FBSDKLoginKit FBSDKCoreKit problem dependency

### ISSUE THREAD

**Issue by lucascorrea** [CocoaPods/Specs#13515]
I am updating my spec to support the new framework of Facebook, but it turns out this error. I have already put in my project 
             //: configuration Debug =
        CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES

That's my spec

        #  Be sure to run `pod spec lint SCFacebook.podspec' to ensure this is a
        #  valid spec and to remove all comments including this before submitting the spec.
        #
        #  To learn more about Podspec attributes see http://docs.cocoapods.org/specification.html
        #  To see working Podspecs in the CocoaPods repo see https://github.com/CocoaPods/Specs/
        #

        Pod::Spec.new do |s|

          s.name         = "SCFacebook"
          s.version      = "4.0"
          s.summary      = "The SCFacebook is a simpler and cleaner to use the api facebook-ios-sdk Objective-C "

          s.description  = <<-DESC
          The SCFacebook is a simpler and cleaner to use the api facebook-ios-sdk Objective-C (https://github.com/facebook/facebook-ios-sdk) to perform login, get friends list, information about the user and posting on the wall with ^Block for iPhone. 
          http://www.lucascorrea.com
                           DESC

          s.homepage     = "http://www.lucascorrea.com"
          s.license      = { :type => "MIT", :text => "SCFacebook is licensed under the MIT License" }

          s.author             = { "Lucas Correa" => "contato@lucascorrea.com" }
          s.platform     = :ios, "7.0"

          s.ios.deployment_target = "7.0"

          s.source       = { :git => "https://github.com/lucascorrea/SCFacebook.git", :tag => "4.0" }

          s.source_files  = "SCFacebook/**/*SCFacebook.{h,m}"

          s.requires_arc = true

          s.dependency "FBSDKCoreKit"
          s.dependency "FBSDKShareKit"
          s.dependency "FBSDKLoginKit"

        end

Error no pod spec lint

         Validating podspec
          -> SCFacebook (4.0)
            - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
            - ERROR | xcodebuild:  FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h:21:9: error: include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKLoginButton' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginConstants.h:21:9: error: include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKLoginConstants' [-Werror,-Wnon-modular-include-in-framework-module]
            - NOTE  | xcodebuild:  SCFacebook/SCFacebook/SCFacebook.h:28:9: fatal error: could not build module 'FBSDKLoginKit'
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKAppGroupContent.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKAppGroupContent' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKAppGroupContent.h:22:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKAppGroupContent' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKAppInviteContent.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKAppInviteContent' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKGameRequestContent.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKGameRequestContent' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKLikeButton.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKLikeButton' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKLikeObjectType.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKLikeObjectType' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKLikeControl.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKLikeControl' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKSharingContent.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKSharingContent' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKSendButton.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKSendButton' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKShareOpenGraphObject.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKShareOpenGraphObject' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKShareButton.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKShareButton' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKShareConstants.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKShareConstants' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKShareDialogMode.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKShareDialogMode' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKShareOpenGraphAction.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKShareOpenGraphAction' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKSharePhoto.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKSharePhoto' [-Werror,-Wnon-modular-include-in-framework-module]
            - ERROR | xcodebuild:  FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKShareVideo.h:21:9: error: include of non-modular header inside framework module 'FBSDKShareKit.FBSDKShareVideo' [-Werror,-Wnon-modular-include-in-framework-module]

Someone with the same problem?

**Comment by NQuinn27** [comment]
+1 I have the same issue. Any light on it?

**Comment by lucascorrea** [comment]
I solved this way. 

     pod spec lint SCFacebook.podspec --use-libraries
