### ISSUE TITLE
My Podspec is visible twice on cocoapods.org

### ISSUE THREAD

**Issue by GerTeunis** [CocoaPods/Specs#13534]
OpenSSL-OSX
Could you have a look at this?

**Comment by keith** [comment]
<img width="1226" alt="screen shot 2015-10-07 at 19 44 14" src="https://cloud.githubusercontent.com/assets/283886/10356407/cd9fff18-6d2b-11e5-9b4c-87bcf86e6161.png">

Looks like whatever you were seeing was fixed.
