### ISSUE TITLE
'pod lib lin' support Swift 2.0  ?

### ISSUE THREAD

**Issue by boyXiong** [CocoaPods/Specs#13544]
‘pod lib lint’    Command support  Swift 2.0 ? 

Why I compile and run is ok,However, according to the command terminal prompt information modification, Xcode7 Error reporting

pod --version
0.38.2

**Comment by keith** [comment]
You should post this on the [main repo](https://github.com/CocoaPods/CocoaPods), when you do you should also post the errors you're seeing.
