### ISSUE TITLE
 You are not allowed to push new versions for this pod.

### ISSUE THREAD

**Issue by boyXiong** [CocoaPods/Specs#13557]
pod trunk info XWSwiftRefresh

XWSwiftRefresh
    - Versions:
      - 0.1.2 (2015-10-11 13:37:49 UTC)
    - Owners:
      - Unclaimed <unclaimed-pods@cocoapods.org>

Why I can't update my code
pod trunk me
  - Name:     boyXiong

This frame is my upload, but I can't change now, and it's not me, what should I do

**Comment by keith** [comment]
You need to claim your pod here: http://blog.cocoapods.org/Claim-Your-Pods/
