### ISSUE TITLE
AWSiOSSDK/Runtime can't find AWS_SBJson.h

### ISSUE THREAD

**Issue by alexandros-s** [CocoaPods/Specs#13560]
AWSiOSSDK/Runtime can't find AWS_SBJson.h.

While the file exists in ThirdParty directory, it fails to link to it.

Podfile example

````
platform :ios, '8.0'

target 'AWSRuntime test' do
  pod 'AWSiOSSDK/Runtime'
end
````

Then I do 

````
#import <AWSiOSSDK/AWSRuntime.h>
````

Podspec 1.7.1

**Comment by alexandros-s** [comment]
Actually I had a go trying to find which version of AWSiOSSDK is working and I had the following findings

* 1.7.1 AWS_SBJson.h is missing
* 1.7.0 AWS_SBJson.h is missing
* 1.6.1 There is a circular dependency between AWSiOSSDK/DynamoDB and AWSiOSSDK/Runtime
* 1.6.0 There is a circular dependency between AWSiOSSDK/DynamoDB and AWSiOSSDK/Runtime
* 1.5.0 There is a circular dependency between AWSiOSSDK/DynamoDB and AWSiOSSDK/Runtime
* 1.4.6 There is a circular dependency between AWSiOSSDK/DynamoDB and AWSiOSSDK/Runtime

**Comment by segiddins** [comment]
Take this up with the maintainers of the AWSiOSSDK pod -- this repository merely holds the spec.
