### ISSUE TITLE
XMPP framework pod not compiling   3.6.4  onward

### ISSUE THREAD

**Issue by hassanraza-maavratech** [CocoaPods/Specs#13573]
Hello 
I don't if any one else found this error since i searched google and found none. I am getting error when updating or installing pod
[!] The platform of the target `Pods` (OS X 10.10) is not compatible with `XMPPFramework (3.6.5)` which has a minimum requirement of iOS 6.0.
and same goes for 3.6.6.
It work fine on 3.6.4.
When i went to see the pod spec file for 3.6.4 . It has support for both "platforms": {
    "ios": "5.0",
    "osx": "10.7"
  },
but 3.6.4 onward osx support is missing. Please help .

**Comment by segiddins** [comment]
You should contact the maintainers of the XMPP podspec.
