### ISSUE TITLE
Google.podspec: Add or remove Measurement subspec

### ISSUE THREAD

**Issue by arielelkin** [CocoaPods/Specs#13580]
1. Integrated Google Analytics pod into my Xcode project by following instructions from [official documentation here](https://developers.google.com/analytics/devguides/collection/ios/v3/?ver=swift).
1. Add `pod 'Google/Analytics'` to Podfile, as instructed
1. Run app, console prints this:
```
App[7610:20] <GMR/INFO> App measurement v.1100000 started
App[7610:5536711] Successfully configured [Analytics].
App[7610:5536711] Failed to configure [].
App[7610:5536711] Subspecs not present, so not configured [AdMob, SignIn, AppInvite, CloudMessaging, Maps].
App[7610:5536711] Subspecs expected to be present [Analytics, Measurement].
```

What is this `Measurement` subspec?? It's not in the pod's list of subspec:

https://github.com/CocoaPods/Specs/blob/master/Specs/Google/1.1.1/Google.podspec.json#L24

Please either add or remove this `Measurement` subspec.

**Comment by keith** [comment]
This needs to be asked upstream

**Comment by arielelkin** [comment]
https://code.google.com/p/analytics-issues/issues/detail?id=762
