### ISSUE TITLE
FBSDKLoginKit CFBundleShortVersionString invalid for iTunes upload

### ISSUE THREAD

**Issue by sfarges** [CocoaPods/Specs#13586]
Hello, version 4.7.0.1 is invalid and prevents upload to itunes connect.
@chrisp-fb  see commit fcd5e8d8063de49eb50d8b5da94f66a194e2a38d
Issues is also identified here https://developers.facebook.com/bugs/828229420628334/
Best regards

**Comment by segiddins** [comment]
This is a bug in CocoaPods that I've recently fixed.
