### ISSUE TITLE
FBSDKLoginKit 4.8.0 is not downloading

### ISSUE THREAD

**Issue by Blahartinger** [CocoaPods/Specs#13629]
cocoapods.org shows 4.7.1 still...

https://cocoapods.org/?q=FBSDKLoginKit

but Core and share are updated: https://cocoapods.org/pods/FBSDKCoreKit https://cocoapods.org/pods/FBSDKShareKit

I reported this to facebook, but they're pointing me to you guys. https://developers.facebook.com/bugs/398701923656519/

**Comment by Blahartinger** [comment]
It appears the cocoapods bot hasn't picked this up and it's been days...

**Comment by Blahartinger** [comment]
@dzhuowen - you updated the other specs..want to update loginkit

**Comment by dzhuowen** [comment]
Thanks for pointing it out @Blahartinger ! Re-pushing FBSDKLoginKit on cocoaPods.

**Comment by orta** [comment]
:+1:
