### ISSUE TITLE
Pod lint erroneously complaining about git tag.

### ISSUE THREAD

**Issue by kstenerud** [CocoaPods/Specs#13651]
I changed the version of my podspec from 2.5 to 2.5.1 and now it's complaining about the git tag.

    Pod::Spec.new do |s|
      s.name     = 'ObjectAL-for-iPhone'
      s.version  = '2.5.1'
      s.license  = { :type => 'MIT', :file => 'ObjectAL/LICENSE.ObjectAL.txt' }
      s.summary  = 'Mac and iOS Audio, minus the headache.'
      s.homepage = 'http://kstenerud.github.io/ObjectAL-for-iPhone/'
      s.authors  = { 'Karl Stenerud' => 'kstenerud@gmail.com' }
      s.source   = { :git => 'https://github.com/kstenerud/ObjectAL-for-iPhone.git', :tag => '2.5' }
      s.source_files = 'ObjectAL/ObjectAL/**/*.[chm]'
      s.public_header_files = 'ObjectAL/ObjectAL/**/*.h'
      s.ios.deployment_target = '4.3'
      s.osx.deployment_target = '10.6'
      s.requires_arc = false
      s.ios.frameworks = 'OpenAL', 'AudioToolbox', 'AVFoundation'
    end

Lint run:

    $ pod spec lint

     -> ObjectAL-for-iPhone (2.5.1)
        - WARN  | The version should be included in the Git tag.

    [!] 2 out of 2 specs failed validation.

Not sure why it's complaining, since the git tag is there:

	$ git tag
	2.3
	2.4
	2.5
	2.5.1
	v1.0
	v1.1
	v2.0
	v2.1
	v2.2

**Comment by keith** [comment]
```

**Comment by kstenerud** [comment]
Maybe make the error message a little more clear instead? That would reduce the number of questions regarding it.

**Comment by keith** [comment]
Feel free to submit a PR on the [core repo](https://github.com/CocoaPods/Core/blob/c91e84a264ce9ab5fc500cc8bd8ffad9c9ecd3cf/lib/cocoapods-core/specification/linter.rb#L346-L347) updating the copy!
